### ISSUE TITLE
have to think of a way to use a loop to take inputs for multiple vehicles

### ISSUE THREAD

**Issue by PandaSupremacy** [tatwamasidotexe/Prototype-for-Techno.Hack-2022#4]

**Comment by tatwamasidotexe** [comment]
tried using a loop and a dictionary to access and store individual details regarding each of the n vehicles owned by the user. but im getting a valueerror while trying to convert number of vehicles to int? check that out and see if you can fix.

buggy code is on master branch, do not merge with main before fixing it.
